### PR TITLE
Ignoring incorrectly specified DarkShieldBottom in DP2 files. Fixes #53

### LINKED ISSUE #53: Workaround needed for incorrect specification of masked areas in DP2 files
zodiacfml posted this about clipped blacks for DP2.

http://www.dpreview.com/forums/post/56198531

After examining the X3F file sent to me, I have come to the conclusion that DarkShieldBottom is specified incorrectly in DP2 files. It partially coincides with the active image. This leads to overestimation of the black level, and thus clipping. The same occurs with x3f-examples/dp2_a.x3f.

I suppose we could work around this by ignoring DarkShieldBottom for DP2.

### PR DESCRIPTION
**Pull request by erikrk**

### CODE REVIEW

File: src/x3f_process.c [hunk 1]
```diff
@@ -68,14 +68,20 @@ static int get_black_level(x3f_t *x3f,
   uint64_t *black_sum;
   double *black_sum_sqdev;
   int pixels, i;
+  /* Workaround for bug in DP2 firmware. DarkShieldBottom is specified
+     incorrectly and thus ingnored. */
+  char *cammodel;
+  int use_bottom = !x3f_get_prop_entry(x3f, "CAMMODEL", &cammodel) ||
+    strcmp(cammodel, "SIGMA DP2");
```
Comment (mmroden) [inline src/x3f_process.c]: stupid question-- there's no potential capitalization issues, ie, across different firmware versions?

Comment (erikrk) [inline src/x3f_process.c]: The PROP metadata is mostly uppercase. I would expect it to be
consistent.
